### PR TITLE
Updates the DB connection example to use pandas

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Pandas simplifies the code and results in a pretty table output.

### CODE REVIEW

**Comment by znmeb** [comment]
Speaking of pandas, is there a pandas tool to read / write Excel spreadsheets? If we're getting data that way it would be quite useful. Let me know and I'll put it in the builds for next week.

**Comment by sanjuroj** [comment]
xlrd and xlwt are not pandas specific, but they will read and write excel files.  [There are others](http://www.python-excel.org/) that may be a bit newer.

**Comment by joehand** [comment]
You can [read](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html) and [write](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_excel.html) excel directly from pandas (it uses xlrd internally i think).

`pandas.read_excel()` or `dataframe.to_excel()`

**Comment by znmeb** [comment]
Well ... if pandas has it built in I don't see any reason to install anything else - the pandas install will grab whatever it's using

**Pull request merged**
